#!/bin/bash

set -e

host="localhost"
user="tarifia"
password="tarifia"
test_database="tarifia_test"

if ! PGPASSWORD=$password psql -h "$host" -U "$user" -d "postgres" -tAc "SELECT 1 FROM pg_database WHERE datname='$test_database'" | grep -q 1; then
  PGPASSWORD=$password psql -h "$host" -U "$user" -d "postgres" -c "CREATE DATABASE $test_database;"
else
  echo "Database $test_database already exists."
fi
