"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from tarifia_sdk.types import BaseModel
from tarifia_sdk.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class CheckoutLinksDeleteRequestTypedDict(TypedDict):
    id: str
    r"""The checkout link ID."""


class CheckoutLinksDeleteRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The checkout link ID."""
