"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from tarifia_sdk.types import BaseModel
from tarifia_sdk.utils import FieldMetadata, QueryParamMetadata
from typing_extensions import Annotated, TypedDict


class CustomerPortalCustomersCheckEmailUpdateRequestTypedDict(TypedDict):
    token: str


class CustomerPortalCustomersCheckEmailUpdateRequest(BaseModel):
    token: Annotated[
        str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]
