"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from tarifia_sdk.types import BaseModel
from tarifia_sdk.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class CustomerSeatsGetClaimInfoRequestTypedDict(TypedDict):
    invitation_token: str


class CustomerSeatsGetClaimInfoRequest(BaseModel):
    invitation_token: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
