"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
import httpx
from tarifia_sdk.models import TarifiaError
from tarifia_sdk.types import BaseModel
from tarifia_sdk.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal, Optional
from typing_extensions import Annotated


class UnauthorizedData(BaseModel):
    detail: str

    ERROR: Annotated[
        Annotated[
            Literal["Unauthorized"], AfterValidator(validate_const("Unauthorized"))
        ],
        pydantic.Field(alias="error"),
    ] = "Unauthorized"


@dataclass(unsafe_hash=True)
class Unauthorized(TarifiaError):
    data: UnauthorizedData = field(hash=False)

    def __init__(
        self,
        data: UnauthorizedData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
