"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .customer import Customer, CustomerTypedDict
from datetime import datetime
from tarifia_sdk.types import BaseModel
from tarifia_sdk.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal
from typing_extensions import Annotated, TypedDict


class WebhookCustomerUpdatedPayloadTypedDict(TypedDict):
    r"""Sent when a customer is updated.

    This event is fired when the customer details are updated.

    If you want to be notified when a customer subscription or benefit state changes, you should listen to the `customer_state_changed` event.

    **Discord & Slack support:** Basic
    """

    timestamp: datetime
    data: CustomerTypedDict
    type: Literal["customer.updated"]


class WebhookCustomerUpdatedPayload(BaseModel):
    r"""Sent when a customer is updated.

    This event is fired when the customer details are updated.

    If you want to be notified when a customer subscription or benefit state changes, you should listen to the `customer_state_changed` event.

    **Discord & Slack support:** Basic
    """

    timestamp: datetime

    data: Customer

    TYPE: Annotated[
        Annotated[
            Literal["customer.updated"],
            AfterValidator(validate_const("customer.updated")),
        ],
        pydantic.Field(alias="type"),
    ] = "customer.updated"
