"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from .sdkconfiguration import SDKConfiguration
from tarifia_sdk.customer_session_sdk import CustomerSessionSDK
from tarifia_sdk.downloadables import Downloadables
from tarifia_sdk.tarifia_benefit_grants import TarifiaBenefitGrants
from tarifia_sdk.tarifia_customer_meters import TarifiaCustomerMeters
from tarifia_sdk.tarifia_customers import TarifiaCustomers
from tarifia_sdk.tarifia_license_keys import TarifiaLicenseKeys
from tarifia_sdk.tarifia_members import TarifiaMembers
from tarifia_sdk.tarifia_orders import TarifiaOrders
from tarifia_sdk.tarifia_organizations import TarifiaOrganizations
from tarifia_sdk.tarifia_subscriptions import TarifiaSubscriptions
from tarifia_sdk.seats import Seats
from tarifia_sdk.wallets import Wallets
from typing import Optional


class CustomerPortal(BaseSDK):
    benefit_grants: TarifiaBenefitGrants
    customers: TarifiaCustomers
    customer_meters: TarifiaCustomerMeters
    seats: Seats
    customer_session: CustomerSessionSDK
    downloadables: Downloadables
    license_keys: TarifiaLicenseKeys
    members: TarifiaMembers
    orders: TarifiaOrders
    organizations: TarifiaOrganizations
    subscriptions: TarifiaSubscriptions
    wallets: Wallets

    def __init__(
        self, sdk_config: SDKConfiguration, parent_ref: Optional[object] = None
    ) -> None:
        BaseSDK.__init__(self, sdk_config, parent_ref=parent_ref)
        self.sdk_configuration = sdk_config
        self._init_sdks()

    def _init_sdks(self):
        self.benefit_grants = TarifiaBenefitGrants(
            self.sdk_configuration, parent_ref=self.parent_ref
        )
        self.customers = TarifiaCustomers(
            self.sdk_configuration, parent_ref=self.parent_ref
        )
        self.customer_meters = TarifiaCustomerMeters(
            self.sdk_configuration, parent_ref=self.parent_ref
        )
        self.seats = Seats(self.sdk_configuration, parent_ref=self.parent_ref)
        self.customer_session = CustomerSessionSDK(
            self.sdk_configuration, parent_ref=self.parent_ref
        )
        self.downloadables = Downloadables(
            self.sdk_configuration, parent_ref=self.parent_ref
        )
        self.license_keys = TarifiaLicenseKeys(
            self.sdk_configuration, parent_ref=self.parent_ref
        )
        self.members = TarifiaMembers(self.sdk_configuration, parent_ref=self.parent_ref)
        self.orders = TarifiaOrders(self.sdk_configuration, parent_ref=self.parent_ref)
        self.organizations = TarifiaOrganizations(
            self.sdk_configuration, parent_ref=self.parent_ref
        )
        self.subscriptions = TarifiaSubscriptions(
            self.sdk_configuration, parent_ref=self.parent_ref
        )
        self.wallets = Wallets(self.sdk_configuration, parent_ref=self.parent_ref)
